config/routes.rb
Rails.application.routes.draw do

  resources :books

  devise_for :users

  root 'pages#home'

  get 'dashboard' => 'pages#dashboard'

  post '/payer/:slug', to: 'transactions#create', as: :payer
  get '/pickup/:slug', to: 'transactions#pickup', as: :pickup

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    can :read, :all # any user can display the book library
    can :manage, Book do |book|
      book.try(:user) == user
    end
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/book.rb
class Book < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  belongs_to :user
  has_many :sales

  has_attached_file :image
  validates_attachment_content_type :image,
  content_type:  /^image\/(png|gif|jpeg|jpg)/,
  message: "Seulement les images de type gif, png, jpg, jpeg"

  has_attached_file :resource
  validates_attachment_content_type :resource,
  content_type:  ['application/pdf'],
  message: "Seulement les documents PDF"

  validates :image, attachment_presence: true
  validates :resource, attachment_presence: true

  validates_numericality_of :price,
  greater_than: 49, message: "Montant doit être supérieur à 50 cents"

end

app/models/sale.rb
class Sale < ActiveRecord::Base
  before_create :populate_guid

  belongs_to :book

  private
  def populate_guid
    self.guid = SecureRandom.uuid()
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :timeoutable

  has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to books_path, alert: "Accès non Authorisé"
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.where(availability: true)
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
    authorize! :manage, @book
  end

  # POST /books
  # POST /books.json
  def create
    @book = current_user.books.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Nouvel Ouvrage creé avec succès' }
        #format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        #format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    authorize! :manage, @book
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Ouvrage mis à jour.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    authorize! :manage, @book
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Ouvrage Supprimé' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:name, :author, :description, :price, :availability, :image, :resource)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: [:dashboard]

  def home
    #if current_user
      #redirect_to books_path
    #end
  end

  def dashboard
    @books = current_user.books
    @purchased = Sale.where(buyer_email: current_user.email)
    @sales = Sale.where(seller_email: current_user.email)
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

  def create
    book = Book.find_by!(slug: params[:slug])
    token = params[:stripeToken]

    begin
      # Charge the Card
      charge = Stripe::Charge.create(
          amount: book.price,
          currency: "usd",
          card: token,
          description: current_user.email
      )
      # Proceed to the Sale
      @sale = book.sales.create!(buyer_email: current_user.email, seller_email: book.user.email)
      # Redirect user to the pickup url
      redirect_to pickup_url(guid: @sale.guid)
      # Rescue any error if it occurs
      rescue Stripe::CardError => e
        flash[:error] = e.message
        redirect_to book_path(book)

    end

  end

  def pickup
    @sale = Sale.find_by!(guid: params[:guid])
    @book = @sale.book

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/books/_book.html.erb
<div class="col-sm-6 col-md-3">
  <div class="thumbnail">
    <%= link_to book_path(book) do %>
    <%= image_tag book.image.url(:original), class: "img-responsive" %>
    <% end %>
        <div class="caption">
          <h4 class="text-centered"><%= book.name %></h4>
          <p class="text-centered">$<%= book.price.to_f / 100 %></p>
          <div class="btn btn-group">
            <%= link_to "<i class='fa fa-eye'></i> Preview".html_safe, book_path(book), class: "btn btn-success" %>

            <%= form_tag payer_path(slug: book.slug) do %>
                <script
                    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                    data-amount="<%= book.price %>"
                    data-name="RodWOOKO-PAYEMENT"
                    data-description="<%= book.name %>"
                    data-email="<%= current_user.email %>" >
                </script>
            <% end %>

          </div>
        </div>
  </div>
</div>

app/views/books/_form.html.erb
<%= simple_form_for(@book, html: {class: "form-signin"}) do |f| %>
  <%= f.error_notification %>

    <%= f.input :name, autofocus: true, required: true, label: false, placeholder: "Nom ou Titre", input_html: {class: "form-control"} %>
    <%= f.input :author, required: true, label: false, placeholder: "Auteur", input_html: { class: "form-control"} %>
    <%= f.input :description, required: true, label: false, placeholder: "Description", input_html: { class: "form-control", rows: 5} %>
    <%= f.input :price, required: true, label: false, placeholder: "Prix en Dollar US", input_html: {class: "form-control"} %>
    <p>Image de Préview: <%= f.input :image, required: true, label: false, input_html: {class: "form-control"} %></p>
    <p>Fichier PDF: <%= f.input :resource, required: true, label: false, input_html: {class: "form-control"} %></p>
    <h5 class="text-center">Disponible: <%= f.input :availability, required: true, label: false %></h5>
    <%= f.button :submit, class: "btn btn-info btn-block" %>

<% end %>

app/views/books/edit.html.erb
<h1 class="text-center"> Modifier Ouvrage </h1>

<%= render 'form' %>

  <%= link_to "<strong><i class='fa fa-hand-o-left'></i> Retour</strong>".html_safe, books_path %> |
  <%= link_to "<strong><i class='fa fa-eye'></i> Preview</strong>".html_safe, @book %>

app/views/books/index.html.erb
<div class="container">
  <div class="row">
    <h2 class="text-centered">Librairie</h2>

    <%= render @books%>

  </div>
</div>

<%= link_to "<strong>Nouvel Ouvrage</strong>".html_safe, new_book_path %>

app/views/books/new.html.erb
<h1 class="text-center">Nouvel Ouvrage</h1>

<%= render 'form' %>

<%= link_to "<strong><i class='fa fa-hand-o-left'></i> Retour</strong>".html_safe, books_path %>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-5">
      <%= image_tag @book.image.url(:original), class: "img-responsive" %>
    </div>
    <div class="col-md-7">
      <h2 class="text-centered"><%= @book.name %></h2>
      <h5><strong>Auteur:</strong> <%= @book.author %></h5>
      <p class="justify"><strong>Description:</strong> <%= @book.description %></p>
      <h4 class="text-centerd">Prix: $<%= @book.price.to_f / 100 %></h4>

      <div class="btn btn-group">
            <%= form_tag payer_path(slug: @book.slug) do %>
            <script
            src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
            data-amount="<%= @book.price %>"
            data-name="RodWOOKO-PAYEMENT"
            data-description="<%= @book.name %>"
            data-email="<%= current_user.email %>" >
            </script>
        <% end %>
      </div>

    </div>

    </div>
</div>

<%= link_to "<strong><i class='fa fa-hand-o-left'></i> Retour</strong>".html_safe, books_path %> |
<%= link_to "<strong><i class='fa fa-pencil-square-o'></i> Modifier</strong>".html_safe, edit_book_path(@book) %> |
<%= link_to "<strong><i class='fa fa-trash-o'></i> Supprimer</strong>".html_safe, book_path(@book), method: :delete, data: { confirm: "Etes-vous Sure?" } %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "<i class='fa fa-leanpub'></i> RodWOOKO".html_safe, root_path, class:"navbar-brand" %>
    </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
              <li><%= link_to "<i class='fa fa-cubes'></i> Dashboard".html_safe, dashboard_path %></li>
              <li><%= link_to "<i class='fa fa-book'></i> Nouvel Ouvrage".html_safe, new_book_path %></li>
              <li><%= link_to "<i class='fa fa-university'></i> Librairie".html_safe, books_path %></li>
              <li><%= link_to "<i class='fa fa-cogs'></i> Configuration".html_safe, edit_user_registration_path %></li>
              <li><%= link_to "<i class='fa fa-sign-out'></i> Logout".html_safe, destroy_user_session_path, method: :delete %></li>
          <% else %>
              <li><%= link_to "<i class='fa fa-building'></i> About".html_safe, "#" %></li>
              <li><%= link_to "<i class='fa fa-key'></i> Login".html_safe, new_user_session_path %></li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rodwooko - La Solution Livres en Ligne</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "layouts/navbar" %>
<div class="container">

  <% if flash[:notice] %>
      <div class="alert alert-success fade-in">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= notice %>
      </div>
  <% end %>

  <% if flash[:alert] %>
      <div class="alert alert-info fade-in">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= alert %>
      </div>
  <% end %>

<%= yield %>
</div>

</body>
</html>

app/views/pages/_achats.html.erb
<table class="table">
  <thead>
  <tr>
    <th>Date</th>
    <th>Nom du Livre</th>
    <th></th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @purchased.each do |sale| %>
      <tr>
        <td><%= time_ago_in_words(sale.created_at) %></td>
        <td><%= link_to sale.book.name, book_path(sale.book.slug) %></td>
        <td><%= link_to " <i class='fa fa-download'></i> Télécharger ".html_safe, pickup_url(sale.book.slug, guid: sale.guid), class: "label label-primary"%></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/pages/_ouvrages.html.erb
<table class="table">
  <thead>
  <tr>
    <th>Id</th>
    <th>Nom</th>
    <th>Disponible</th>
    <th>Prix</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @books.each do |book| %>
      <tr>
        <td><%= book.id %></td>
        <td><%= link_to book.name, book_path(book) %></td>
        <td><%= book.availability %></td>
        <td>$<%= book.price.to_f / 100 %></td>
        <td><%= link_to " <i class='fa fa-pencil-square-o'></i> Editer".html_safe, edit_book_path(book), class: "label label-info"%></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/pages/_ventes.html.erb
<table class="table">
  <thead>
  <tr>
    <th>Date</th>
    <th>Nom du Livre</th>
    <th>Acheteur</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @sales.each do |sale| %>
      <tr>
        <td><%= time_ago_in_words(sale.created_at) %></td>
        <td><%= link_to sale.book.name, book_path(sale.book.slug) %></td>
        <td><%= sale.buyer_email %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/pages/dashboard.html.erb
<div class="container">
  <div class="row">
    <h3 class="text-center label-primary">Dashboard</h3>

    <div class="col-md-4">
      <h4 class="text-center"><strong>Mes Ouvrages </strong><%= link_to "Ajouter Ouvrage", new_book_path, class: "label label-success" %></h4>
      <%= render "ouvrages" %>
    </div>

    <div class="col-md-4">
      <h4 class="text-center"><strong>Mes Achats</strong></h4>
      <%= render "achats" %>
    </div>

    <div class="col-md-4">
      <h4 class="text-center"><strong>Mes Ouvrages Vendus</strong></h4>
      <%= render "ventes" %>
    </div>

  </div>
</div>

app/views/pages/home.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-6 col-lg-offset-3">
      <div class="jumbotron text-center">
        <h1><i class="fa fa-leanpub"></i>RodWOOKO</h1>

        <% if current_user %>
            <p>Bienvenue sur la meuilleur Platforme de Gestion et de Vente de Livres en Ligne.</p>
            <%= link_to "<i class='fa fa-university'></i> Visiter Librairie".html_safe, books_path, class: "btn btn-primary btn-lg btn-md btn-block" %>
            <%= link_to "<i class='fa fa-book'></i> Nouvel Ouvrage".html_safe, new_book_path, class: "btn btn-success btn-lg btn-md btn-block" %>
        <% else %>
            <p>La Platforme de Gestion et de Vente de Livres en Ligne.</p>
            <%= link_to "<i class='fa fa-pencil-square-o'></i> Sign up".html_safe, new_user_registration_path, class: "btn btn-success btn-lg btn-md btn-block" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/transactions/pickup.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-6 col-lg-offset-3">
      <div class="jumbotron text-center">
        <h1><i class="fa fa-leanpub"></i>RodWOOKO</h1>

        <% if current_user %>
            <div class="alert alert-info" role="alert"><strong>Votre payement à été validé. Le numéro de votre commande est: </strong><%= @sale.guid %></div>
            <%= link_to "<i class='fa fa-download'></i> Téléchargez Ouvrage".html_safe, @book.resource.url, class: "btn btn-success btn-lg btn-md btn-block" %>
        <% else %>
            <p>La Platforme de Gestion et de Vente de Livres en Ligne.</p>
            <%= link_to "<i class='fa fa-pencil-square-o'></i> Sign up".html_safe, new_user_registration_path, class: "btn btn-success btn-lg btn-md btn-block" %>
        <% end %>
      </div>
    </div>
  </div>
</div>